name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Grab the Ansible Version to use.
        id: vars
        run: echo "::set-output name=version::$(cat version)"

      - name: Build the Docker Image.
        run: docker build . --build-arg ANSIBLE_VERSION=${{ steps.vars.outputs.version }} --tag ${{ steps.getversion.outputs.version }}-ci:$(date +%s)
