name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Grab the Ansible Version to use.
        run: cat version.properties >> $ANSIBLE_VERSION
      - name: Build the Docker Image.
        run: docker build . --build-arg ANSIBLE_VERSION=%ANSIBLE_VERSION% --tag $ANSIBLE_VERSION-ci:$(date +%s)
