name: Release Image

on:
  release:
    types: [published]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to DockerHub.
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u dcjulian29 --password-stdin

      - name: Grab the Ansible Version to use.
        id: vars
        #run: echo "::set-output name=version::$(echo ${GITHUB_REF:10})"
        run: echo "::set-output name=version::$(cat VERSION)"

      - name: Build the Docker Image.
        run: docker build . --build-arg ANSIBLE_VERSION=${{ steps.vars.outputs.version }} --tag ${{ steps.vars.outputs.version }}

      - name: Tag the image as latest.
        run: docker tag dcjulian29/ansible:${{ steps.vars.outputs.version }} dcjulian29/ansible:latest

      - name: Publish Docker image to DockerHub.
        run: docker push dcjulian29/ansible --all-tags
